CREATE TABLE USUARIO(
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    SENHA VARCHAR(1000)
);

CREATE TABLE CATEGORIA(
    CD_CATEGORIA INT PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE RESTAURANTE(
    CD_RESTAURANTE INT PRIMARY KEY,
    CNPJ VARCHAR(14),
    NOME VARCHAR(255),
    TELEFONE VARCHAR(20),
    NUMERO VARCHAR(10),
    CEP VARCHAR(8),
    BAIRRO VARCHAR(255),
    RUA VARCHAR(255),
    CIDADE VARCHAR(255)
);

CREATE TABLE CUPOM(
    CD_CUPOM INT PRIMARY KEY,
    TIPO VARCHAR(255),
    VALIDADE DATE
);

CREATE TABLE TELEFONE(
    CPF VARCHAR(11),
    NUMERO VARCHAR(20),
    CONSTRAINT PK_TELEFONE PRIMARY KEY(CPF, NUMERO),
    CONSTRAINT FK_TEL_USUARIO FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);

CREATE TABLE CLIENTE(
    CPF VARCHAR(11),
    RUA VARCHAR(255),
    CIDADE VARCHAR(255),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(255),
    CEP VARCHAR(8),
    CONVIDADO VARCHAR(11),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF),
    CONSTRAINT FK_CLI_USUARIO FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
    CONSTRAINT FK_CLI_CONVIDADO FOREIGN KEY (CONVIDADO) REFERENCES CLIENTE(CPF)
);

CREATE TABLE ENTREGADOR(
    CPF VARCHAR(11),
    NOTA FLOAT,
    VEICULO VARCHAR(255),
    PLACA VARCHAR(10),
    CONSTRAINT PK_ENTREGADOR PRIMARY KEY(CPF),
    CONSTRAINT FK_ENT_USUARIO FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);

CREATE TABLE PERTENCE(
    CD_RESTAURANTE INT,
    CD_CATEGORIA INT,
    CONSTRAINT PK_PERTENCE PRIMARY KEY (CD_RESTAURANTE, CD_CATEGORIA),
    CONSTRAINT FK_PERT_REST FOREIGN KEY (CD_RESTAURANTE) REFERENCES RESTAURANTE(CD_RESTAURANTE),
    CONSTRAINT FK_PERT_CAT FOREIGN KEY (CD_CATEGORIA) REFERENCES CATEGORIA(CD_CATEGORIA)
);

CREATE TABLE PRODUTO(
    CD_PRODUTO INT PRIMARY KEY,
    NOME VARCHAR(255),
    DESCRICAO VARCHAR(255),
    NOTA FLOAT,
    PRECO FLOAT,
    CD_RESTAURANTE INT,
    CONSTRAINT FK_PROD_REST FOREIGN KEY (CD_RESTAURANTE) REFERENCES RESTAURANTE(CD_RESTAURANTE)
);

CREATE TABLE PEDIDO(
    CD_PEDIDO INT PRIMARY KEY,
    VALOR_TOTAL FLOAT,
    STATUS VARCHAR(255),
    DATA DATE,
    CD_RESTAURANTE INT,
    CPF_CLIENTE VARCHAR(11),
    CPF_ENTREGADOR VARCHAR(11),
    CD_CUPOM INT,
    CONSTRAINT FK_PED_REST FOREIGN KEY (CD_RESTAURANTE) REFERENCES RESTAURANTE(CD_RESTAURANTE),
    CONSTRAINT FK_PED_CLI FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF),
    CONSTRAINT FK_PED_ENT FOREIGN KEY (CPF_ENTREGADOR) REFERENCES ENTREGADOR(CPF),
    CONSTRAINT FK_PED_CUP FOREIGN KEY (CD_CUPOM) REFERENCES CUPOM(CD_CUPOM)
);

CREATE TABLE CONTEM(
    CD_PEDIDO INT,
    CD_PRODUTO INT,
    CONSTRAINT PK_CONTEM PRIMARY KEY (CD_PEDIDO, CD_PRODUTO),
    CONSTRAINT FK_CONT_PED FOREIGN KEY (CD_PEDIDO) REFERENCES PEDIDO(CD_PEDIDO),
    CONSTRAINT FK_CONT_PROD FOREIGN KEY (CD_PRODUTO) REFERENCES PRODUTO(CD_PRODUTO)
);

CREATE TABLE PAGAMENTO(
    CD_PAGAMENTO INT PRIMARY KEY,
    TIPO VARCHAR(255),
    SUBTIPO_CARTAO VARCHAR(255),
    DATA_HORA DATETIME,
    VALOR FLOAT,
    CD_PEDIDO INT,
    CONSTRAINT FK_PAG_PED FOREIGN KEY (CD_PEDIDO) REFERENCES PEDIDO(CD_PEDIDO)
);

CREATE TABLE HISTORICO_STATUS(
    CD_HISTORICO INT PRIMARY KEY,
    CD_PEDIDO INT,
    DESCRICAO VARCHAR(255),
    DATA_HORA DATETIME,
    CONSTRAINT FK_HIST_PED FOREIGN KEY (CD_PEDIDO) REFERENCES PEDIDO(CD_PEDIDO)
);

CREATE TABLE AVALIA(
    CD_AVALIACAO INT PRIMARY KEY,
    CPF_CLIENTE VARCHAR(11),
    CD_PEDIDO INT,
    CD_PRODUTO INT,
    NOTA FLOAT,
    COMENTARIO TEXT,
    DATA DATE,
    CONSTRAINT FK_AVA_CLI FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF),
    CONSTRAINT FK_AVA_CONTEM FOREIGN KEY (CD_PEDIDO, CD_PRODUTO) REFERENCES CONTEM(CD_PEDIDO, CD_PRODUTO)
);