CREATE TABLE IF NOT EXISTS LOG_PEDIDOS (
    CD_LOG      INT PRIMARY KEY AUTO_INCREMENT,
    CD_PEDIDO   INT,
    CPF_CLIENTE VARCHAR(14),
    VALOR_TOTAL FLOAT,
    DATA_HORA   DATETIME DEFAULT CURRENT_TIMESTAMP,
    OPERACAO    VARCHAR(50)
);

DELIMITER $$
CREATE TRIGGER trg_log_novo_pedido
AFTER INSERT
ON PEDIDO
FOR EACH ROW
BEGIN
    INSERT INTO LOG_PEDIDOS (CD_PEDIDO, CPF_CLIENTE, VALOR_TOTAL, DATA_HORA, OPERACAO)
    VALUES (NEW.CD_PEDIDO, NEW.CPF_CLIENTE, NEW.VALOR_TOTAL, NOW(), 'NOVO PEDIDO');
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_atualizar_nota_entregador
AFTER INSERT
ON AVALIA
FOR EACH ROW
BEGIN
    DECLARE v_cpf_entregador VARCHAR(14);
    DECLARE v_nova_nota      FLOAT;

    SELECT CPF_ENTREGADOR INTO v_cpf_entregador
    FROM PEDIDO
    WHERE CD_PEDIDO = NEW.CD_PEDIDO;

    IF v_cpf_entregador IS NOT NULL THEN

        SELECT AVG(a.NOTA) INTO v_nova_nota
        FROM AVALIA a
        JOIN PEDIDO p ON a.CD_PEDIDO = p.CD_PEDIDO
        WHERE p.CPF_ENTREGADOR = v_cpf_entregador;

        UPDATE ENTREGADOR
        SET NOTA = ROUND(v_nova_nota, 2)
        WHERE CPF = v_cpf_entregador;

    END IF;

END $$
DELIMITER ;