CREATE VIEW VIEW_FATURAMENTO_PEDIDOS_CONCLUIDOS AS
SELECT
    ped.CD_PEDIDO,
    rest.NOME AS RESTAURANTE,
    u.NOME AS CLIENTE,
    pag.TIPO AS FORMA_PAGAMENTO,
    pag.VALOR AS VALOR_PAGO,
    pag.DATA_HORA
FROM
    PAGAMENTO pag
JOIN
    PEDIDO ped ON pag.CD_PEDIDO = ped.CD_PEDIDO
JOIN
    RESTAURANTE rest ON ped.CD_RESTAURANTE = rest.CD_RESTAURANTE
JOIN
    USUARIO u ON ped.CPF_CLIENTE = u.CPF
WHERE
    ped.STATUS = 'Concluido';



CREATE VIEW VIEW_ENTREGADORES_DESTAQUE AS
SELECT
    u.NOME,
    e.VEICULO,
    e.NOTA
FROM
    ENTREGADOR e
JOIN
    USUARIO u ON e.CPF = u.CPF
WHERE
    e.NOTA > (SELECT AVG(NOTA) FROM ENTREGADOR);



CREATE INDEX idx_pedido_cpf_cliente
ON PEDIDO (CPF_CLIENTE);

CREATE INDEX idx_produto_rest_nota
ON PRODUTO (CD_RESTAURANTE, NOTA);